name: Docker Image Build and Deploy

on:
  push:
    branches:
      - main # Trigger workflow on push to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: abdullahdaniyal1234
          password: superflies2026

      # Build the backend Docker image
      - name: Build Backend Docker Image
        run: |
          docker build -t abdullahdaniyal1234/medical-imaging-backend:latest .

      # Build the frontend Docker image
      - name: Build Frontend Docker Image
        run: |
          docker build -f frontend/Dockerfile -t abdullahdaniyal1234/medical-imaging-frontend:latest .
          
      # Push the backend Docker image to Docker Hub
      - name: Push Backend Docker Image to Docker Hub
        run: |
          docker push abdullahdaniyal1234/medical-imaging-backend:latest

      # Push the frontend Docker image to Docker Hub
      - name: Push Frontend Docker Image to Docker Hub
        run: |
          docker push abdullahdaniyal1234/medical-imaging-frontend:latest
